# Generated by Django 5.2.15 on 2026-06-10 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_solicitante', models.CharField(max_length=30)),
                ('tipo_servicio', models.CharField(max_length=50)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ACTIVO', 'Activo'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', max_length=9)),
                ('cantidad_bulto', models.IntegerField()),
                ('observacion', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
